package kalman

import java.io.{File, PrintWriter}

import chisel3._
import chiseltest._
import org.scalatest.flatspec.AnyFlatSpec
import org.scalatest.matchers.should.Matchers

import scala.io.Source

// Replays the synthetic measurement series generated by `golden/kalman_ref.py`
// (`make kf-golden`) through the DUT, respecting the Decoupled ready/busy handshake,
// and writes the hardware's output to vectors/kalman_hw_output.csv for diff_kalman.py
// to bit-exact-diff against vectors/kalman_golden_fixed.csv.
//
// Config constants (DT, Q0, Q1, R) must match golden/kalman_ref.py's module-level
// constants exactly, since they feed both models' recursions identically.
class KalmanFilterReplayTest extends AnyFlatSpec with ChiselScalatestTester with Matchers {
  val DT = 1.0
  val Q0 = 0.05
  val Q1 = 0.01
  val R  = 2.0

  val vectorsDir = new File("../vectors")
  val inputFile  = new File(vectorsDir, "kalman_input.csv")
  val outputFile = new File(vectorsDir, "kalman_hw_output.csv")

  "KalmanFilter" should "replay the golden input series and match its recursion bit-for-bit at the algorithm level" in {
    assume(
      inputFile.exists(),
      s"${inputFile.getPath} not found -- run `make kf-golden` (or `python golden/kalman_ref.py`) first",
    )

    val rows = Source.fromFile(inputFile).getLines().drop(1).map { line =>
      val Array(seqStr, zStr) = line.split(",")
      (seqStr.trim.toLong, zStr.trim.toDouble)
    }.toList

    test(new KalmanFilter()) { dut =>
      dut.io.cfg.dt.poke(FixedPoint.toFixed(DT).S(32.W))
      dut.io.cfg.q0.poke(FixedPoint.toFixed(Q0).S(32.W))
      dut.io.cfg.q1.poke(FixedPoint.toFixed(Q1).S(32.W))
      dut.io.cfg.r.poke(FixedPoint.toFixed(R).S(32.W))

      val results = scala.collection.mutable.ArrayBuffer.empty[(Long, BigInt, BigInt)]

      for ((seq, z) <- rows) {
        dut.io.in.bits.z.poke(FixedPoint.toFixed(z).S(32.W))
        dut.io.in.bits.seqNum.poke(seq.U(32.W))
        dut.io.in.bits.valid.poke(true.B)
        dut.io.in.valid.poke(true.B)

        var waited = 0
        while (!dut.io.in.ready.peek().litToBoolean && waited < 100) {
          dut.clock.step(1)
          waited += 1
        }
        dut.io.in.ready.expect(true.B, s"input never became ready for seq=$seq")
        dut.clock.step(1) // accept
        dut.io.in.valid.poke(false.B)

        var c = 0
        while (!dut.io.out.valid.peek().litToBoolean && c < 100) {
          dut.clock.step(1)
          c += 1
        }
        dut.io.out.valid.expect(true.B, s"no output for seq=$seq within 100 cycles")
        dut.io.out.seqNum.expect(seq.U)

        val priceRaw = dut.io.out.price.peek().litValue
        val driftRaw = dut.io.out.drift.peek().litValue
        results += ((seq, priceRaw, driftRaw))
      }

      vectorsDir.mkdirs()
      val w = new PrintWriter(outputFile)
      try {
        w.println("seq,price_raw,drift_raw")
        for ((seq, price, drift) <- results) {
          w.println(s"$seq,$price,$drift")
        }
      } finally {
        w.close()
      }

      results.length shouldBe rows.length
    }
  }
}
